# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product/image'),
        ),
    ]
