# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addition',
            field=models.TextField(blank=True),
        ),
    ]
